---
hostname: Spine1 #necessary field
interfaces:
  swp1:
    ip address:
      - 10.1.1.1/30
    shutdown: no
  swp2:
    ip address:
      - 10.1.2.1/30
    shutdown: no
  swp3:
    ip address:
      - 10.1.3.1/30
    shutdown: no
  swp4:
    ip address:
      - 10.1.4.1/30
    shutdown: no
loopback:
  ip address:
    - 1.1.1.11/32
ospf:
  router-id: 1.1.1.11
  interfaces:
    lo:
      area: 0.0.0.0
      passive interface: yes
    swp1:
      area: 0.0.0.0
      passive interface: no
      network: point-to-point
    swp2:
      area: 0.0.0.0
      passive interface: no
      network: point-to-point
    swp3:
      area: 0.0.0.0
      passive interface: no
      network: point-to-point
    swp4:
      area: 0.0.0.0
      passive interface: no
      network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.11
  neighbors:
    1.1.1.101:
      remote: 100
      update: lo
      activate evpn: yes
      rrc: yes #route-reflector-client
      evpn rrc: yes #evpn route-reflector-client
    1.1.1.102:
      remote: 100
      update: lo
      activate evpn: yes
      rrc: yes
      evpn rrc: yes
    1.1.1.103:
      remote: 100
      update: lo
      activate evpn: yes
      rrc: yes
      evpn rrc: yes
    1.1.1.104:
      remote: 100
      update: lo
      activate evpn: yes
      rrc: yes
      evpn rrc: yes
    1.1.1.12:
      remote: 100
      update: lo
...
---
hostname: Leaf1 #necessary field
interfaces:
  swp1:
    ip address:
      - 10.1.1.2/30
    shutdown: no
  swp2:
    ip address:
      - 10.2.1.2/30
    shutdown: no
loopback:
  ip address:
    - 1.1.1.101/32
ospf:
  router-id: 1.1.1.101
  interfaces:
    lo:
      area: 0.0.0.0
      passive interface: yes
    swp1:
      area: 0.0.0.0
      passive interface: no
      network: point-to-point
    swp2:
      area: 0.0.0.0
      passive interface: no
      network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.101
  neighbors:
    1.1.1.11:
      remote: 100
      update: lo
      activate evpn: yes
    1.1.1.12:
      remote: 100
      update: lo
      activate evpn: yes
  advertise-all-vni: yes
vlan:
  10:
    ip address:
      - 192.168.1.254/24
  20:
    ip address:
      - 192.168.2.254/24
bridge:
  ports:
    - swp3
    - swp4
  vids:
    10:
      bridge access:
        - swp3
    20:
      bridge access:
        - swp4
vxlan:
  vnis:
    vni10:
      id: 10010
      bridge access: 10
      bridge learning: no
      local-tunnelip: 1.1.1.101
      remoteip: null
    vni20:
      id: 10020
      bridge access: 20
      bridge learning: no
      local-tunnelip: 1.1.1.101
...