---
hostname: Spine1
node type: FRR
device type: linux
ip address: 10.0.0.11
username: root
password: root
secret: root
port: 22
interfaces:
  eth1:
    add ip address:
      - 10.1.1.1/30
    del ip address:
      - null
    shutdown: no
  eth2:
    add ip address:
      - 10.1.2.1/30
    shutdown: no
  eth3:
    add ip address:
      - 10.1.3.1/30
    shutdown: no
  eth4:
    add ip address:
      - 10.1.4.1/30
    shutdown: no
  lo:
    add ip address:
      - 1.1.1.11/32
    shutdown: no
ospf:
  router-id: 1.1.1.11
  area:
    0.0.0.0:
      interfaces:
        lo:
          passive interface: yes
        eth1:
          passive interface: no
          network: point-to-point
        eth2:
          passive interface: no
          network: point-to-point
        eth3:
          passive interface: no
          network: point-to-point
        eth4:
          passive interface: no
          network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.11
  neighbors:
    1.1.1.101:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes #evpn route-reflector-client
    1.1.1.102:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes
    1.1.1.103:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes
    1.1.1.104:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes
    1.1.1.12:
      remote: 100
      update: lo
copy to startup-config: true
...
---
hostname: Spine2
node type: FRR
device type: linux
ip address: 10.0.0.12
username: root
password: root
secret: root
port: 22
interfaces:
  eth1:
    add ip address:
      - 10.2.1.1/30
    del ip address:
      - null
    shutdown: no
  eth2:
    add ip address:
      - 10.2.2.1/30
    shutdown: no
  eth3:
    add ip address:
      - 10.2.3.1/30
    shutdown: no
  eth4:
    add ip address:
      - 10.2.4.1/30
    shutdown: no
  lo:
    add ip address:
      - 1.1.1.12/32
    shutdown: no
ospf:
  router-id: 1.1.1.12
  area:
    0.0.0.0:
      interfaces:
        lo:
          passive interface: yes
        eth1:
          passive interface: no
          network: point-to-point
        eth2:
          passive interface: no
          network: point-to-point
        eth3:
          passive interface: no
          network: point-to-point
        eth4:
          passive interface: no
          network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.12
  neighbors:
    1.1.1.101:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes #evpn route-reflector-client
    1.1.1.102:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes
    1.1.1.103:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes
    1.1.1.104:
      remote: 100
      update: lo
      activate evpn: yes
      evpn rrc: yes
    1.1.1.11:
      remote: 100
      update: lo
copy to startup-config: true
...
---
hostname: Leaf1
node type: Cumulus
device type: linux
ip address: 10.0.0.101
username: cumulus
password: cumulus1
secret: cumulus1
port: 22
hard clear config: yes #clear current config before applying new (recommended in this version)
interfaces:
  swp1:
    add ip address:
      - 10.1.1.2/30
    del ip address:
      - null
    shutdown: no
  swp2:
    add ip address:
      - 10.2.1.2/30
    shutdown: no
loopback:
  add ip address:
    - 1.1.1.101/32
  shutdown: no
ospf:
  router-id: 1.1.1.101
  area:
    0.0.0.0:
      interfaces:
        lo:
          add ospf: yes
          passive interface: yes
        swp1:
          add ospf: yes
          passive interface: no
          network: point-to-point
        swp2:
          add ospf: yes
          passive interface: no
          network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.101
  neighbors:
    1.1.1.11:
      remote: 100
      update: lo
      activate evpn: yes
    1.1.1.12:
      remote: 100
      update: lo
      activate evpn: yes
  advertise-all-vni: yes
vlan:
  10:
    ip address:
      - 192.168.1.254/24
  20:
    ip address:
      - 192.168.2.254/24
bridge:
  ports:
    - swp3
    - swp4
  vids:
    10:
      bridge access:
        - swp3
    20:
      bridge access:
        - swp4
vxlan:
  vnis:
    vni10:
      id: 10010
      bridge access: 10
      bridge learning: no
      local-tunnelip: 1.1.1.101
      remoteip: null
    vni20:
      id: 10020
      bridge access: 20
      bridge learning: no
      local-tunnelip: 1.1.1.101
commit: true
...
---
hostname: Leaf2
node type: Cumulus
device type: linux
ip address: 10.0.0.102
username: cumulus
password: cumulus1
secret: cumulus1
port: 22
hard clear config: yes #clear current config before applying new (recommended in this version)
interfaces:
  swp1:
    add ip address:
      - 10.1.2.2/30
    del ip address:
      - null
    shutdown: no
  swp2:
    add ip address:
      - 10.2.2.2/30
    shutdown: no
loopback:
  add ip address:
    - 1.1.1.102/32
  shutdown: no
ospf:
  router-id: 1.1.1.102
  area:
    0.0.0.0:
      interfaces:
        lo:
          add ospf: yes
          passive interface: yes
        swp1:
          add ospf: yes
          passive interface: no
          network: point-to-point
        swp2:
          add ospf: yes
          passive interface: no
          network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.102
  neighbors:
    1.1.1.11:
      remote: 100
      update: lo
      activate evpn: yes
    1.1.1.12:
      remote: 100
      update: lo
      activate evpn: yes
  advertise-all-vni: yes
vlan:
  20:
    ip address:
      - 192.168.2.254/24
bridge:
  ports:
    - swp4
  vids:
    20:
      bridge access:
        - swp4
vxlan:
  vnis:
    vni20:
      id: 10020
      bridge access: 20
      bridge learning: no
      local-tunnelip: 1.1.1.102
commit: true
...
---
hostname: Leaf3
node type: Cumulus
device type: linux
ip address: 10.0.0.103
username: cumulus
password: cumulus1
secret: cumulus1
port: 22
hard clear config: yes #clear current config before applying new (recommended in this version)
interfaces:
  swp1:
    add ip address:
      - 10.1.3.2/30
    del ip address:
      - null
    shutdown: no
  swp2:
    add ip address:
      - 10.2.3.2/30
    shutdown: no
loopback:
  add ip address:
    - 1.1.1.103/32
  shutdown: no
ospf:
  router-id: 1.1.1.103
  area:
    0.0.0.0:
      interfaces:
        lo:
          add ospf: yes
          passive interface: yes
        swp1:
          add ospf: yes
          passive interface: no
          network: point-to-point
        swp2:
          add ospf: yes
          passive interface: no
          network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.103
  neighbors:
    1.1.1.11:
      remote: 100
      update: lo
      activate evpn: yes
    1.1.1.12:
      remote: 100
      update: lo
      activate evpn: yes
  advertise-all-vni: yes
vlan:
  10:
    ip address:
      - 192.168.1.254/24
bridge:
  ports:
    - swp3
  vids:
    10:
      bridge access:
        - swp3
vxlan:
  vnis:
    vni10:
      id: 10010
      bridge access: 10
      bridge learning: no
      local-tunnelip: 1.1.1.103
      remoteip: null
commit: true
...
---
hostname: Leaf4
node type: Cumulus
device type: linux
ip address: 10.0.0.104
username: cumulus
password: cumulus1
secret: cumulus1
port: 22
hard clear config: yes #clear current config before applying new (recommended in this version)
interfaces:
  swp1:
    add ip address:
      - 10.1.4.2/30
    del ip address:
      - null
    shutdown: no
  swp2:
    add ip address:
      - 10.2.4.2/30
    shutdown: no
loopback:
  add ip address:
    - 1.1.1.104/32
  shutdown: no
ospf:
  router-id: 1.1.1.104
  area:
    0.0.0.0:
      interfaces:
        lo:
          add ospf: yes
          passive interface: yes
        swp1:
          add ospf: yes
          passive interface: no
          network: point-to-point
        swp2:
          add ospf: yes
          passive interface: no
          network: point-to-point
bgp:
  as: 100
  router-id: 1.1.1.104
  neighbors:
    1.1.1.11:
      remote: 100
      update: lo
      activate evpn: yes
    1.1.1.12:
      remote: 100
      update: lo
      activate evpn: yes
  advertise-all-vni: yes
vlan:
  10:
    ip address:
      - 192.168.1.254/24
  20:
    ip address:
      - 192.168.2.254/24
bridge:
  ports:
    - swp3
    - swp4
  vids:
    10:
      bridge access:
        - swp3
    20:
      bridge access:
        - swp4
vxlan:
  vnis:
    vni10:
      id: 10010
      bridge access: 10
      bridge learning: no
      local-tunnelip: 1.1.1.104
      remoteip: null
    vni20:
      id: 10020
      bridge access: 20
      bridge learning: no
      local-tunnelip: 1.1.1.104
commit: true
...